apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-deployment
  namespace: dev
  labels:
    app: whoami-app
spec:
  replicas: 3 # Chạy 3 Pod rải đều ra 3 Node K3d
  selector:
    matchLabels:
      app: whoami-app
  template:
    metadata:
      labels:
        app: whoami-app
    spec:
      affinity:
        podAntiAffinity: # Luật ép rải đều Pod, nhưng lần này chỉ áp dụng cho Pod whoami
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - whoami-app
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: whoami
        image: traefik/whoami:latest
        ports:
        - containerPort: 80