apiVersion: v1
kind: Service
metadata:
  name: whoami-service
  namespace: dev
spec:
  selector:
    app: whoami-app # Khớp chính xác với label app: whoami-app ở file Deployment trên
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP